/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms.radniDnevnik;

import database.DBBRadniDnevnik;
import domain.RadniDnevnik;
import domain.RadniSati;
import enumeration.Mesec;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author dobri
 */
public class AzurirajRadniDnevnikForma extends javax.swing.JDialog {

    private RadniDnevnik radniDnevnik;

    /**
     * Creates new form DodajRadniDnevnik
     */
    public AzurirajRadniDnevnikForma(java.awt.Dialog parent, boolean modal, RadniDnevnik radniDnevnik) {
        super(parent, modal);
        initComponents();
        this.radniDnevnik = radniDnevnik;
        comboMesec.setModel(new DefaultComboBoxModel<Mesec>(Mesec.values()));
        initFields();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSifraRadnogDnevnika = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSifraZaposlenog = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSifraKontrolera = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboMesec = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtGodina = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtStandardni = new javax.swing.JTextField();
        txtPrekovremeni = new javax.swing.JTextField();
        check = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("sifraRadnogDnevnika:");

        txtSifraRadnogDnevnika.setEnabled(false);

        jLabel2.setText("sifraZaposlenog:");

        jLabel3.setText("sifraKontrolera:");

        jLabel4.setText("mesec:");

        jLabel5.setText("godina:");

        jButton1.setText("Azuriraj radni dnevnik");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("ukupniRadniSati:");

        txtStandardni.setEnabled(false);

        txtPrekovremeni.setEnabled(false);

        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSifraRadnogDnevnika)
                            .addComponent(txtSifraZaposlenog, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(txtSifraKontrolera, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(comboMesec, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtGodina, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtStandardni, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrekovremeni, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSifraRadnogDnevnika, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSifraZaposlenog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSifraKontrolera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboMesec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtGodina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtStandardni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPrekovremeni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(check)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int sifraZaposlenog = Integer.parseInt(txtSifraZaposlenog.getText());
        int sifraKontrolera = Integer.parseInt(txtSifraKontrolera.getText());
        Mesec mesec = (Mesec) comboMesec.getSelectedItem();
        int godina = Integer.parseInt(txtGodina.getText());
        radniDnevnik.setSifraZaposlenog(sifraZaposlenog);
        radniDnevnik.setSifraKontrolera(sifraKontrolera);
        radniDnevnik.setMesec(mesec);
        radniDnevnik.setGodina(godina);
        try {
            if (check.isSelected()) {
                int standardniSati = Integer.parseInt(txtStandardni.getText());
                int prekovremeniSati = Integer.parseInt(txtPrekovremeni.getText());
                radniDnevnik.setRadniSati(new RadniSati(standardniSati, prekovremeniSati));
                DBBRadniDnevnik.azurirajRadniDnevnikSaRadnimSatima(radniDnevnik);
            } else {
                DBBRadniDnevnik.azurirajRadniDnevnikBezRadnihSati(radniDnevnik);
            }
            RadniDnevnikForma forma = (RadniDnevnikForma) getParent();
            forma.initTables();
            dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        txtStandardni.setEnabled(check.isSelected());
        txtPrekovremeni.setEnabled(check.isSelected());
    }//GEN-LAST:event_checkActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox check;
    private javax.swing.JComboBox<Mesec> comboMesec;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtGodina;
    private javax.swing.JTextField txtPrekovremeni;
    private javax.swing.JTextField txtSifraKontrolera;
    private javax.swing.JTextField txtSifraRadnogDnevnika;
    private javax.swing.JTextField txtSifraZaposlenog;
    private javax.swing.JTextField txtStandardni;
    // End of variables declaration//GEN-END:variables

    private void initFields() {
        txtSifraRadnogDnevnika.setText(String.valueOf(radniDnevnik.getSifraRadnogDnevnika()));
        txtSifraZaposlenog.setText(String.valueOf(radniDnevnik.getSifraZaposlenog()));
        txtSifraKontrolera.setText(String.valueOf(radniDnevnik.getSifraKontrolera()));
        comboMesec.setSelectedItem(radniDnevnik.getMesec());
        txtGodina.setText(String.valueOf(radniDnevnik.getGodina()));
        txtStandardni.setText(String.valueOf(radniDnevnik.getRadniSati().getStandardniSati()));
        txtPrekovremeni.setText(String.valueOf(radniDnevnik.getRadniSati().getPrekovremeniSati()));
    }
}
